import pyautogui

pyautogui.press('Win')
pyautogui.sleep(1)
pyautogui.write('Google Chrome', interval= 0.2)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.hotkey('alt', 'd')
pyautogui.press('Enter')
pyautogui.write('instagram.com')
pyautogui.sleep(1)
pyautogui.press('Enter')
pyautogui.sleep(0.5)
pyautogui.press('tab')
pyautogui.sleep(0.5)
pyautogui.write('o @')
pyautogui.sleep(0.5)
pyautogui.press('tab')
pyautogui.write('senha')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.click()
pyautogui.sleep(30)
pyautogui.hotkey('alt', 'f4')